#!/bin/bash
# hermes-backup-manifest — managed by evilbot fleet/ansible/satellite.yml
#
# WHY THIS EXISTS
# Package-manager payloads (docker image layers, snap squashfs, flatpak runtimes)
# are large and re-downloadable. Backing them up wastes space and restore time.
# But if you drop them without recording WHAT was installed, a rebuild is guesswork.
#
# So: record the list, back up the local state, skip the re-downloadable bulk.
#   recorded here  -> docker images, snaps, flatpaks, apt manual selections
#   backed up      -> docker named volumes, /var/snap app data, ~/.var/app, /etc
#   NOT backed up  -> /var/lib/docker/overlay2, /var/lib/snapd, /var/lib/flatpak
#
# Output goes to /var/lib/hermes-backup/manifests/, which IS in the backup path
# list, so the manifests travel inside the snapshot they describe.
#
# Every section degrades gracefully: a host without docker just writes nothing
# for docker. Never fails the backup — a manifest problem must not stop a backup.
set -uo pipefail

OUT=/var/lib/hermes-backup/manifests
mkdir -p "$OUT" || exit 0
chmod 0700 "$OUT" 2>/dev/null
chmod 0700 /var/lib/hermes-backup 2>/dev/null

ts() { date -u +%Y-%m-%dT%H:%M:%SZ; }
hdr() { printf '# %s\n# generated %s on %s\n' "$1" "$(ts)" "$(hostname)"; }

# --- docker ------------------------------------------------------------------
# Images are pullable IF they came from a registry. An image built locally and
# never pushed is NOT recoverable from this list — it is flagged so a human sees it.
if command -v docker >/dev/null 2>&1 && docker info >/dev/null 2>&1; then
  {
    hdr "docker images (repo:tag@digest). A <none> repo or missing digest means"
    echo "# the image is LOCAL-ONLY and cannot be re-pulled — see local-only-images below."
    docker image ls --digests --format '{{.Repository}}:{{.Tag}}@{{.Digest}}' 2>/dev/null | sort
  } > "$OUT/docker-images.txt"

  {
    hdr "docker images with no registry digest — NOT recoverable by pulling"
    docker image ls --digests --format '{{.Repository}}:{{.Tag}}@{{.Digest}} {{.ID}}' 2>/dev/null \
      | awk '$0 ~ /@<none>/ || $0 ~ /^<none>/ {print}' | sort
  } > "$OUT/docker-local-only-images.txt"

  {
    hdr "docker containers (all states) with their image and restart policy"
    docker ps -a --format '{{.Names}}\t{{.Image}}\t{{.Status}}\t{{.Ports}}' 2>/dev/null | sort
  } > "$OUT/docker-containers.txt"

  {
    hdr "docker named volumes — these ARE backed up (/var/lib/docker/volumes)"
    docker volume ls --format '{{.Driver}}\t{{.Name}}' 2>/dev/null | sort
  } > "$OUT/docker-volumes.txt"

  {
    hdr "docker bind mounts — host paths containers depend on."
    echo "# Check each one is inside the backup path list; a bind mount outside it"
    echo "# is silently unprotected container state."
    docker ps -aq 2>/dev/null | while read -r c; do
      docker inspect "$c" --format \
        '{{$n := .Name}}{{range .Mounts}}{{if eq .Type "bind"}}{{$n}}	{{.Source}}	{{.Destination}}	{{if .RW}}rw{{else}}ro{{end}}
{{end}}{{end}}' 2>/dev/null
    done | grep -v '^[[:space:]]*$' | sort -u
  } > "$OUT/docker-bind-mounts.txt"

  {
    hdr "docker inspect (full) for every container — recreates run flags"
    docker ps -aq 2>/dev/null | xargs -r docker inspect 2>/dev/null
  } > "$OUT/docker-inspect.json"

  {
    hdr "docker compose projects known to the daemon"
    docker ps -a --filter 'label=com.docker.compose.project' \
      --format '{{.Label "com.docker.compose.project"}}\t{{.Label "com.docker.compose.project.working_dir"}}\t{{.Label "com.docker.compose.project.config_files"}}' \
      2>/dev/null | sort -u
  } > "$OUT/docker-compose-projects.txt"

  # --- local-only images: EXPORT, don't just list -----------------------------
  # An image with no registry digest was built here and cannot be re-pulled.
  # Listing it is useless for recovery, so save the actual layers.
  #
  # DEFAULT OFF, and deliberately so. Learned the hard way 2026-09-28: a developer
  # workstation accumulates dozens of local-only images that are BUILD ARTEFACTS,
  # not state — 57 of them, mostly `samcli/lambda-python` and CDK asset images,
  # several GB each. They are regenerated by re-running the build, so exporting
  # them wastes tens of GB per night and defeats the point of a thin backup.
  # Worse, on a work-adjacent machine those images can contain EMPLOYER code, and
  # copying them to the NAS silently moves employer data onto home storage.
  #
  # So this only runs when a host opts in, and only for images the operator has
  # named. Set in host_vars:
  #     hbm_local_image_max_mb: 2048          # per-image cap
  #     hbm_local_image_total_mb: 8192        # total budget for the whole export
  #     hbm_local_image_include: 'myapp|mytool'   # REQUIRED regex allowlist
  : "${HBM_LOCAL_IMAGE_MAX_MB:=0}"
  : "${HBM_LOCAL_IMAGE_TOTAL_MB:=8192}"
  : "${HBM_LOCAL_IMAGE_INCLUDE:=}"
  IMGDIR="$OUT/../local-images"
  # NB: this must run BEFORE the .skipped file is appended to, or entries
  # accumulate forever across runs.
  rm -f "$IMGDIR/.skipped"
  if [ "$HBM_LOCAL_IMAGE_MAX_MB" -gt 0 ] && [ -n "$HBM_LOCAL_IMAGE_INCLUDE" ]; then
    mkdir -p "$IMGDIR" 2>/dev/null
    RUNNING_MB=0
    # Resolve local-only images to IDs, then to their tags.
    mapfile -t LOCAL_IDS < <(
      docker image ls --digests --format '{{.ID}} {{.Repository}}:{{.Tag}} {{.Digest}}' 2>/dev/null \
        | awk '$3 == "<none>" {print $1}' | sort -u
    )
    KEEP=""
    for id in "${LOCAL_IDS[@]:-}"; do
      [ -n "$id" ] || continue
      tag=$(docker image inspect "$id" --format '{{if .RepoTags}}{{index .RepoTags 0}}{{end}}' 2>/dev/null)
      # Allowlist: skip anything the operator did not explicitly name.
      printf '%s' "${tag:-$id}" | grep -Eq "$HBM_LOCAL_IMAGE_INCLUDE" || continue
      bytes=$(docker image inspect "$id" --format '{{.Size}}' 2>/dev/null || echo 0)
      mb=$(( bytes / 1024 / 1024 ))
      safe=$(printf '%s' "${tag:-$id}" | tr -c 'A-Za-z0-9._-' '_')
      f="$IMGDIR/$safe.tar"
      if [ "$mb" -gt "$HBM_LOCAL_IMAGE_MAX_MB" ]; then
        echo "SKIPPED ${tag:-$id} (${mb}MB > ${HBM_LOCAL_IMAGE_MAX_MB}MB per-image cap)" >> "$IMGDIR/.skipped"
        continue
      fi
      if [ $(( RUNNING_MB + mb )) -gt "$HBM_LOCAL_IMAGE_TOTAL_MB" ]; then
        echo "SKIPPED ${tag:-$id} (${mb}MB would exceed ${HBM_LOCAL_IMAGE_TOTAL_MB}MB total budget)" >> "$IMGDIR/.skipped"
        continue
      fi
      RUNNING_MB=$(( RUNNING_MB + mb ))
      # Only re-export when the image id changed, so unchanged images stay
      # deduplicated by restic and the backup does not grow every night.
      if [ ! -f "$f.id" ] || [ "$(cat "$f.id" 2>/dev/null)" != "$id" ]; then
        # Save by TAG, not by ID: `docker save <id>` produces a tar with no
        # RepoTags, so `docker load` restores a dangling image and
        # `docker run <name>` then fails with "pull access denied". Verified
        # 2026-09-28. Fall back to the id only for genuinely untagged images.
        ref="${tag:-$id}"
        [ "$ref" = "<none>:<none>" ] && ref="$id"
        # Write to a temp file and move into place, so an interrupted run never
        # leaves a truncated tar that looks like a valid export.
        tmpf=$(mktemp "$IMGDIR/.tmp-$safe.XXXXXX") || continue
        if docker save "$ref" -o "$tmpf" 2>/dev/null; then
          mv -f "$tmpf" "$f" && printf '%s' "$id" > "$f.id"
        else
          rm -f "$tmpf"
        fi
      fi
      KEEP="$KEEP $safe"
    done
    # Drop exports for images that no longer exist locally, plus any temp files
    # left by a killed run.
    rm -f "$IMGDIR"/.tmp-* 2>/dev/null
    for f in "$IMGDIR"/*.tar; do
      [ -e "$f" ] || continue
      b=$(basename "$f" .tar)
      case " $KEEP " in *" $b "*) ;; *) rm -f "$f" "$f.id" ;; esac
    done
    {
      hdr "locally-built images EXPORTED as tars (restore: docker load -i <file>)"
      echo "# allowlist: ${HBM_LOCAL_IMAGE_INCLUDE}"
      echo "# caps: ${HBM_LOCAL_IMAGE_MAX_MB}MB per image, ${HBM_LOCAL_IMAGE_TOTAL_MB}MB total; used ${RUNNING_MB}MB"
      ls -la "$IMGDIR" 2>/dev/null | grep -E '\.tar$'
      [ -f "$IMGDIR/.skipped" ] && cat "$IMGDIR/.skipped"
    } > "$OUT/docker-local-image-exports.txt"
  else
    rm -rf "$IMGDIR" 2>/dev/null
    {
      hdr "local-only image export is DISABLED on this host"
      echo "# Local-only images cannot be re-pulled, but on a dev workstation most"
      echo "# are build artefacts that are cheaper to rebuild than to store, and on a"
      echo "# work machine they may hold employer code. Nothing is exported unless"
      echo "# host_vars sets BOTH hbm_local_image_max_mb > 0 AND an"
      echo "# hbm_local_image_include allowlist regex."
      echo "# The images themselves are still listed in docker-local-only-images.txt."
    } > "$OUT/docker-local-image-exports.txt"
  fi
fi

# --- snap --------------------------------------------------------------------
# /var/lib/snapd holds the squashfs images (large, re-downloadable).
# /var/snap holds per-snap system data (small) and IS backed up.
if command -v snap >/dev/null 2>&1; then
  {
    hdr "installed snaps (name, version, rev, tracking, publisher)"
    echo "# Re-install with: snap install <name> --channel=<tracking> [--revision=<rev>]"
    snap list --all 2>/dev/null
  } > "$OUT/snap-list.txt"
fi

# --- flatpak -----------------------------------------------------------------
if command -v flatpak >/dev/null 2>&1; then
  {
    hdr "installed flatpaks (system + user)"
    echo "# Re-install with: flatpak install <origin> <application>//<branch>"
    echo "## remotes"
    flatpak remotes --columns=name,url 2>/dev/null
    echo "## system"
    flatpak list --system --columns=application,version,branch,origin,installation 2>/dev/null
    echo "## user"
    flatpak list --user --columns=application,version,branch,origin,installation 2>/dev/null
  } > "$OUT/flatpak-list.txt"
fi

# --- apt ---------------------------------------------------------------------
# Cheap, and it turns an L3 rebuild from archaeology into a one-liner.
if command -v apt-mark >/dev/null 2>&1; then
  {
    hdr "manually-installed apt packages"
    echo "# Re-install with: xargs -a <(grep -v ^# thisfile) apt-get install -y"
    apt-mark showmanual 2>/dev/null | sort
  } > "$OUT/apt-manual.txt"
  {
    hdr "full dpkg selections (exact, including auto-installed)"
    dpkg --get-selections 2>/dev/null
  } > "$OUT/dpkg-selections.txt"
  {
    hdr "apt sources"
    grep -rhs '^[^#]' /etc/apt/sources.list /etc/apt/sources.list.d/ 2>/dev/null | sort -u
  } > "$OUT/apt-sources.txt"
fi

# --- pip/pipx ----------------------------------------------------------------
if command -v pipx >/dev/null 2>&1; then
  { hdr "pipx packages"; pipx list --short 2>/dev/null; } > "$OUT/pipx-list.txt"
fi

# --- disk layout -------------------------------------------------------------
# Not restorable automatically, but an L3 rebuild needs it to recreate partitions
# and fstab UUIDs. This is the single most-missed item in a bare-metal restore.
{
  hdr "block devices, filesystems and mount points at backup time"
  echo "## lsblk"
  lsblk -o NAME,SIZE,FSTYPE,UUID,PARTUUID,MOUNTPOINT 2>/dev/null
  echo "## findmnt (real filesystems)"
  findmnt -rno TARGET,SOURCE,FSTYPE,OPTIONS 2>/dev/null | grep -Ev '^/(proc|sys|dev|run|snap)'
  echo "## blkid"
  blkid 2>/dev/null
  echo "## efi boot entries"
  efibootmgr -v 2>/dev/null
} > "$OUT/disk-layout.txt"

chmod 0600 "$OUT"/* 2>/dev/null
exit 0
