name: IaC CI

on:
  pull_request:
  push:
    branches: [ main, master ]

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    steps:
      - uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform fmt
        run: terraform fmt -check -diff

      - name: Terraform init
        run: terraform init -input=false

      - name: Terraform validate
        run: terraform validate

      # Optional: plan (needs provider creds/secrets)
      # - name: Terraform plan
      #   run: terraform plan -input=false
      #   env:
      #     PM_API_URL: ${{ secrets.PM_API_URL }}
      #     PM_USER: ${{ secrets.PM_USER }}
      #     PM_PASS: ${{ secrets.PM_PASS }}

  ansible:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ansible
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install linters
        run: |
          pip install ansible ansible-lint yamllint

      - name: ansible-lint
        run: ansible-lint .

      - name: yamllint
        run: yamllint .
